import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import connect from "@/lib/dbConnect";
import SessionProvider from "@/components/SessionProvider";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });
const lexend = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Fars Route",
  description: "Generated by Bashir Danish",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const connectToDB = async () => {
    try {
      await connect();
      console.log("Connected to MongoDB 💫");
    } catch (error) {
      console.error("Failed to connect to MongoDB", error);
    }
  };

  connectToDB();
  let locale = await getLocale();
  const messages = await getMessages();
  const isRtl = ['ar', 'he', 'fa', 'ur'].includes(locale);

  return (
    <html lang={locale} dir={isRtl ? 'rtl' : 'ltr'}>
      <SessionProvider>
        <body className={`${inter.className} ${lexend.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
